version: "3.7"

services:
  mongo:
    image: mongo:5.0.6
    restart: always
    container_name: mongodb
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: $DB_USER
      MONGO_INITDB_ROOT_PASSWORD: $DB_PASSWORD
      DB_NAME: $DB_NAME
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASS
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh

volumes:
  db:
